### ISSUE TITLE
Cannot extract the 1.0.8 release package

### ISSUE THREAD

**Issue by fishman8** [bnovakovic/GameList_Converter#4]
I cannot extract the 1.0.8 release packages for all platforms. Please check the files.

**Comment by bnovakovic** [comment]
Thanks for letting me know. I have the same issue. Not sure what happened there. I will remove this release and revert back to the old one until I'm ready for the new one where we will support different locations for gamelist.xml files.

**Comment by bnovakovic** [comment]
Issue is resolved, and new version is live. Thanks a lot for bringing this up!
